10:
  cross: 
    - ""
    - 11
    - ""
    - 14
  tag_id:
    - 161
    - 151
    - 141
    - ""

11:
  cross: 
    - 10
    - ""
    - 12
    - 13
  tag_id:
    - 236
    - 235
    - ""
    - 137

12:
  cross: 
    - 13
    - 11
    - ""
    - 14
  tag_id:
    - 240
    - 239
    - 238
    - ""

13:
  cross: 
    - ""
    - 11
    - 12
    - 14
  tag_id:
    - 241
    - ""
    - 242
    - 243

14:
  cross: 
    - 10
    - 13
    - 12
    - ""
  tag_id:
    - ""
    - 245
    - 246
    - 244

